-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.researcher
(
    id integer NOT NULL,
    "full name" character varying(50) NOT NULL,
    level character varying(50) NOT NULL,
    laboratory_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.object
(
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    distance character varying(50) NOT NULL,
    laboratory_id integer NOT NULL,
    type_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."object type"
(
    id integer NOT NULL,
    type character varying(50) NOT NULL,
    galaxy_location character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.labolatory
(
    id integer NOT NULL,
    "lab name" character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.researcher
    ADD FOREIGN KEY (laboratory_id)
    REFERENCES public.labolatory (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.object
    ADD FOREIGN KEY (type_id)
    REFERENCES public."object type" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.object
    ADD FOREIGN KEY (laboratory_id)
    REFERENCES public.labolatory (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;